const properties = [
  {
    id: 1,
    title: 'HOUSE in Springfield',
    location: '123 Maple St, Springfield, IL',
    property_type: 'House',
    images: ['/images/prop1.png', '/images/prop2.png'],
    latitude: 39.78,
    longitude: -89.64,
    price: 600000,
    bhk: 2,
    owner: { username: 'John', email: 'john@example.com', contact_no: '+1234567890' },
  },
  {
    id: 2,
    title: 'HOUSE in Capital City',
    location: '45 Pine Ave, Capital City, CA',
    property_type: 'House',
    images: ['/images/prop3.png', '/images/prop4.png'],
    latitude: 38.9,
    longitude: -77.03,
    price: 600000,
    bhk: 1,
    owner: { username: 'Ria', email: 'ria@example.com', contact_no: '+1987456321' },
  },
  {
    id: 3,
    title: 'HOUSE in Rivertown',
    location: '202 Birch Rd, Rivertown, TX',
    property_type: 'House',
    images: ['/images/prop5.png', '/images/prop6.png'],
    latitude: 30.15,
    longitude: -95.45,
    price: 500000,
    bhk: 3,
    owner: { username: 'Mia', email: 'mia@example.com', contact_no: '+1876456123' },
  },
  {
    id: 4,
    title: 'HOUSE in 202 Birch Rd',
    location: '202 Birch Rd, Rivertown, TX',
    property_type: 'House',
    images: ['/images/prop7.png', '/images/prop8.png'],
    latitude: 36.15,
    longitude: -95.45,
    price: 700000,
    bhk: 4,
    owner: { username: 'Jess', email: 'jess@example.com', contact_no: '+1234098765' },
  },
  {
    id: 5,
    title: 'APARTMENT in 123 Maple St',
    location: '123 Maple St, Springfield, IL',
    property_type: 'Apartment',
    images: ['/images/prop9.png', '/images/prop10.png'],
    latitude: 30.15,
    longitude: -95.45,
    price: 400000,
    bhk: 3,
    owner: { username: 'James', email: 'james@example.com', contact_no: '+1999888777' },
  },
  {
    id: 6,
    title: 'CONDO in 202 Birch Rd',
    location: '202 Birch Rd, Rivertown, TX',
    property_type: 'Condo',
    images: ['/images/imagecopy.png', '/images/imagecopy8.png'],
    latitude: 35.15,
    longitude: -85.45,
    price: 500000,
    bhk: 3,
    owner: { username: 'Ava', email: 'ava@example.com', contact_no: '+1777888999' },
  },
  {
    id: 7,
    title: 'APARTMENT in 45 Pine Ave',
    location: '45 Pine Ave, Capital City, CA',
    property_type: 'Apartment',
    images: ['/images/imagecopy2.png', '/images/imagecopy9.png'],
    latitude: 33.15,
    longitude: -95.45,
    price: 400000,
    bhk: 2,
    owner: { username: 'Liam', email: 'liam@example.com', contact_no: '+1666777888' },
  },
  {
    id: 8,
    title: 'APARTMENT in 101 Elm Blvd',
    location: '101 Elm Blvd, Lakeside, FL',
    property_type: 'Apartment',
    images: ['/images/imagecopy3.png', '/images/imagecopy10.png'],
    latitude: 30.15,
    longitude: -95.45,
    price: 300000,
    bhk: 1,
    owner: { username: 'Sophia', email: 'sophia@example.com', contact_no: '+1555666777' },
  },
  {
    id: 9,
    title: 'CONDO in 123 Maple St',
    location: '123 Maple St, Springfield, IL',
    property_type: 'Condo',
    images: ['/images/imagecopy4.png', '/images/imagecopy11.png'],
    latitude: 35.25,
    longitude: -95.45,
    price: 600000,
    bhk: 3,
    owner: { username: 'Noah', email: 'noah@example.com', contact_no: '+1444555666' },
  },
  {
    id: 10,
    title: 'CONDO in 101 Elm Blvd',
    location: '101 Elm Blvd, Lakeside, FL',
    property_type: 'Condo',
    images: ['/images/imagecopy5.png', '/images/imagecopy12.png'],
    latitude: 30.15,
    longitude: -95.45,
    price: 700000,
    bhk: 2,
    owner: { username: 'Olivia', email: 'olivia@example.com', contact_no: '+1333444555' },
  },
  {
    id: 11,
    title: 'APARTMENT in 789 Oak Lane',
    location: '789 Oak Lane, Pleasantville, NY',
    property_type: 'Apartment',
    images: ['/images/imagecopy6.png', '/images/imagecopy13.png'],
    latitude: 33.15,
    longitude: -96.45,
    price: 500000,
    bhk: 4,
    owner: { username: 'Ethan', email: 'ethan@example.com', contact_no: '+1222333444' },
  },
  {
    id: 12,
    title: 'CONDO in 789 Oak Lane',
    location: '789 Oak Lane, Pleasantville, NY',
    property_type: 'Condo',
    images: ['/images/imagecopy7.png', '/images/imagecopy14.png'],
    latitude: 34.25,
    longitude: -94.45,
    price: 400000,
    bhk: 2,
    owner: { username: 'Emma', email: 'emma@example.com', contact_no: '+1112223334' },
  },
  {
    id: 13,
    title: 'HOUSE in 123 Maple St',
    location: '123 Maple St, Springfield, IL',
    property_type: 'House',
    images: ['/images/imagecopy.png', '/images/imagecopy15.png'],
    latitude: 37.15,
    longitude: -93.45,
    price: 300000,
    bhk: 3,
    owner: { username: 'Michael', email: 'michael@example.com', contact_no: '+1002003004' },
  },
];

export default properties;
